import React, { useEffect, useMemo, useState } from 'react';
import { Plus, FolderTree, Search, Layers, Package, RefreshCw, ArrowUpRight } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { supabase } from '../lib/supabase';

type Category = { name: string; productCount: number; stock: number; icon: string };
const iconFor = (name: string) => name.includes('بشرة') ? '✨' : name.includes('شعر') ? '💇‍♀️' : name.includes('مكياج') ? '💄' : name.includes('عطر') ? '🌸' : name.includes('شفاه') ? '💋' : '🧴';

export const CategoriesPage: React.FC = () => {
    const navigate = useNavigate();
    const [categories, setCategories] = useState<Category[]>([]);
    const [query, setQuery] = useState('');
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState('');
    const load = async () => { setLoading(true); setError(''); const { data, error: fetchError } = await supabase.from('products').select('category,stock').limit(1000); if (fetchError) setError(fetchError.message); const grouped = new Map<string, Category>(); (data || []).forEach((product: { category?: string; stock?: number }) => { const name = product.category?.trim(); if (!name) return; const current = grouped.get(name) || { name, productCount: 0, stock: 0, icon: iconFor(name) }; current.productCount += 1; current.stock += Number(product.stock || 0); grouped.set(name, current); }); setCategories([...grouped.values()].sort((a, b) => b.productCount - a.productCount)); setLoading(false); };
    useEffect(() => { void load(); }, []);
    const visible = useMemo(() => categories.filter((category) => category.name.includes(query.trim())), [categories, query]);
    const totalProducts = categories.reduce((sum, category) => sum + category.productCount, 0);
    const totalStock = categories.reduce((sum, category) => sum + category.stock, 0);
    return <div className="space-y-8 animate-in fade-in duration-500" dir="rtl">
        <div className="flex flex-col md:flex-row md:items-end justify-between gap-4"><div><h1 className="text-3xl font-black text-slate-900 tracking-tight">التصنيفات والهيكلية</h1><p className="text-slate-500 font-medium mt-1">التصنيفات الحية المستخرجة من منتجات المتجر</p></div><div className="flex gap-3"><button onClick={() => void load()} className="flex items-center gap-2 border border-slate-200 text-slate-600 px-5 py-3 rounded-2xl font-black hover:bg-slate-50 transition-all"><RefreshCw className={`w-5 h-5 ${loading ? 'animate-spin' : ''}`} /> تحديث</button><button onClick={() => navigate('/products/new')} className="flex items-center gap-2 bg-brand-blue text-white px-6 py-3 rounded-2xl font-black hover:bg-blue-700 transition-all shadow-lg shadow-blue-200"><Plus className="w-5 h-5" /> إضافة منتج بتصنيف جديد</button></div></div>
        <div className="grid grid-cols-1 lg:grid-cols-4 gap-8"><div className="space-y-6"><div className="bg-white p-8 rounded-3xl border border-slate-100 shadow-sm"><h3 className="text-lg font-black text-slate-900 mb-6 flex items-center gap-2"><Layers className="w-5 h-5 text-brand-blue" /> إحصائيات الكتالوج</h3><div className="space-y-6"><div className="flex justify-between items-center text-sm font-bold"><span className="text-slate-500">تصنيفات مستخدمة</span><span className="text-slate-900 bg-slate-100 px-3 py-1 rounded-lg">{categories.length}</span></div><div className="flex justify-between items-center text-sm font-bold text-brand-blue"><span>إجمالي المنتجات</span><span className="bg-blue-50 px-3 py-1 rounded-lg">{totalProducts}</span></div><div className="flex justify-between items-center text-sm font-bold text-emerald-600"><span>إجمالي المخزون</span><span className="bg-emerald-50 px-3 py-1 rounded-lg">{totalStock}</span></div></div></div><div className="bg-slate-900 p-8 rounded-3xl shadow-xl"><h3 className="text-white font-black mb-4 flex items-center gap-2"><FolderTree className="w-5 h-5 text-emerald-400" /> ملاحظة التشغيل</h3><p className="text-slate-400 text-sm font-medium leading-relaxed">يتم إنشاء التصنيف تلقائياً عند حفظ منتج جديد باسم تصنيف غير مستخدم. عدّلي التصنيف من نموذج المنتج ليظهر هنا وفي تطبيق العميل.</p></div></div>
            <div className="lg:col-span-3"><div className="bg-white p-4 rounded-3xl border border-slate-100 shadow-sm mb-6 flex items-center gap-4"><div className="flex-1 relative"><Search className="w-5 h-5 text-slate-400 absolute right-3 top-1/2 -translate-y-1/2" /><input value={query} onChange={(event) => setQuery(event.target.value)} type="text" placeholder="البحث عن تصنيف..." className="w-full pr-10 pl-4 py-2.5 bg-slate-50 border border-slate-100 rounded-xl text-sm font-medium outline-none focus:ring-2 focus:ring-brand-blue" /></div></div>{error && <div className="mb-5 rounded-2xl bg-red-50 border border-red-100 p-4 text-red-700 font-bold">تعذر تحميل التصنيفات: {error}</div>}{loading ? <div className="bg-white rounded-3xl p-12 text-center text-slate-500 font-bold">جاري تحميل التصنيفات...</div> : visible.length === 0 ? <div className="bg-white rounded-3xl p-12 text-center"><Package className="w-12 h-12 mx-auto text-slate-300" /><h3 className="mt-4 font-black text-slate-800">لا توجد تصنيفات مطابقة</h3><p className="text-slate-500 mt-2">أضيفي منتجاً من زر إضافة منتج بتصنيف جديد.</p></div> : <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-6">{visible.map((category) => <div key={category.name} className="bg-white p-6 rounded-3xl border border-slate-100 shadow-sm hover:shadow-md transition-all group border-b-4 border-b-slate-50 hover:border-b-brand-blue"><div className="flex justify-between items-start mb-6"><div className="text-3xl bg-slate-50 w-14 h-14 rounded-2xl flex items-center justify-center border border-slate-100 group-hover:bg-blue-50 group-hover:border-blue-100 transition-colors">{category.icon}</div><button onClick={() => navigate(`/products?category=${encodeURIComponent(category.name)}`)} className="p-2 text-slate-400 hover:text-brand-blue transition-colors" title="عرض المنتجات"><ArrowUpRight className="w-5 h-5" /></button></div><h4 className="text-xl font-black text-slate-900 mb-1">{category.name}</h4><p className="text-[10px] text-slate-400 font-bold uppercase tracking-widest mb-4">تصنيف المنتجات</p><div className="flex items-center justify-between mt-auto pt-6 border-t border-slate-50"><span className="text-xs font-black text-slate-600">{category.productCount} منتج</span><span className="text-xs font-bold text-emerald-600">{category.stock} في المخزون</span></div></div>)}</div>}</div></div>
    </div>;
};
