import React, { useEffect, useState } from 'react';
import { Bell, CheckCheck, ChevronLeft, Loader2 } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { supabase } from '../../lib/supabase';
import { useAuth } from '../../context/AuthContext';

type CustomerNotification = { id: string; type: string; title_ar: string; body_ar: string; payload: { url?: string } | null; is_read: boolean; created_at: string };

export const CustomerNotificationsPage: React.FC = () => {
  const { user } = useAuth(); const navigate = useNavigate();
  const [items, setItems] = useState<CustomerNotification[]>([]); const [loading, setLoading] = useState(true);
  const load = async () => { if (!user) return; setLoading(true); const { data } = await supabase.from('customer_notifications').select('id,type,title_ar,body_ar,payload,is_read,created_at').order('created_at', { ascending: false }).limit(60); setItems((data || []) as CustomerNotification[]); setLoading(false); };
  useEffect(() => { void load(); }, [user]);
  useEffect(() => { if (!user) return; const channel = supabase.channel(`customer-notifications-${user.id}`).on('postgres_changes', { event: 'INSERT', schema: 'public', table: 'customer_notifications', filter: `customer_id=eq.${user.id}` }, (payload) => setItems((current) => [payload.new as CustomerNotification, ...current])).subscribe(); return () => { void supabase.removeChannel(channel); }; }, [user]);
  const open = async (item: CustomerNotification) => { if (!item.is_read) { await supabase.from('customer_notifications').update({ is_read: true, read_at: new Date().toISOString() }).eq('id', item.id); setItems((current) => current.map((entry) => entry.id === item.id ? { ...entry, is_read: true } : entry)); } const orderNumber = (item.payload as { order_number?: string } | null)?.order_number; if (orderNumber) navigate(`/track-order?order=${encodeURIComponent(orderNumber)}`); else if (item.payload?.url) navigate(item.payload.url); };
  const markAll = async () => { await supabase.from('customer_notifications').update({ is_read: true, read_at: new Date().toISOString() }).eq('is_read', false); setItems((current) => current.map((entry) => ({ ...entry, is_read: true }))); };
  if (loading) return <div className="flex min-h-[50vh] items-center justify-center"><Loader2 className="h-8 w-8 animate-spin text-brand-blue" /></div>;
  const unread = items.filter((item) => !item.is_read).length;
  return <div className="mx-auto max-w-3xl p-4 md:p-8"><header className="mb-7 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><div className="flex items-center gap-3"><div className="rounded-2xl bg-brand-blue-soft p-3 text-brand-blue"><Bell className="h-7 w-7" /></div><div><h1 className="text-2xl font-black text-slate-900">مركز الإشعارات</h1><p className="mt-1 text-sm text-slate-500">تحديثات الطلبات والعروض وعودة المنتجات للمخزون.</p></div></div></div>{unread > 0 && <button onClick={() => void markAll()} className="inline-flex items-center justify-center gap-2 rounded-xl border border-brand-blue-soft bg-white px-4 py-2.5 text-xs font-black text-brand-blue"><CheckCheck className="h-4 w-4" />قراءة الكل ({unread})</button>}</header><section className="overflow-hidden rounded-3xl border border-slate-100 bg-white shadow-sm">{items.length ? <div className="divide-y divide-slate-100">{items.map((item) => <button key={item.id} onClick={() => void open(item)} className={`flex w-full items-start gap-4 p-5 text-right transition hover:bg-slate-50 ${item.is_read ? '' : 'bg-blue-50/40'}`}><div className={`mt-1 h-2.5 w-2.5 shrink-0 rounded-full ${item.is_read ? 'bg-slate-200' : 'bg-brand-blue'}`} /><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-3"><h2 className="font-black text-slate-900">{item.title_ar}</h2><time className="shrink-0 text-[11px] text-slate-400">{new Date(item.created_at).toLocaleDateString('ar-EG')}</time></div><p className="mt-2 text-sm leading-6 text-slate-600">{item.body_ar}</p></div><ChevronLeft className="mt-1 h-4 w-4 shrink-0 text-slate-300" /></button>)}</div> : <div className="p-16 text-center"><Bell className="mx-auto h-12 w-12 text-slate-200" /><p className="mt-4 font-bold text-slate-500">لا توجد إشعارات جديدة.</p><p className="mt-1 text-sm text-slate-400">ستظهر هنا تحديثات طلباتك والمنتجات التي تتابعينها.</p></div>}</section></div>;
};
