import React, { useEffect, useState } from 'react';
import { Gift, Loader2, MinusCircle, PlusCircle, Sparkles } from 'lucide-react';
import { supabase } from '../../lib/supabase';
import { useAuth } from '../../context/AuthContext';

type Ledger = { id: string; points_delta: number; event_type: string; note: string | null; created_at: string; order: { order_number: string | null } | null };

export const LoyaltyPage: React.FC = () => {
    const { user } = useAuth(); const [points, setPoints] = useState(0); const [ledger, setLedger] = useState<Ledger[]>([]); const [loading, setLoading] = useState(true);
    useEffect(() => { if (!user) return; void (async () => { const [profile, history] = await Promise.all([supabase.from('profiles').select('beauty_points').eq('id', user.id).maybeSingle(), supabase.from('loyalty_ledger').select('id,points_delta,event_type,note,created_at,order:orders(order_number)').order('created_at', { ascending: false }).limit(30)]); setPoints(Number(profile.data?.beauty_points || 0)); setLedger((history.data || []) as unknown as Ledger[]); setLoading(false); })(); }, [user]);
    if (loading) return <div className="flex min-h-[50vh] items-center justify-center"><Loader2 className="h-8 w-8 animate-spin text-brand-blue"/></div>;
    return <div className="mx-auto max-w-3xl p-4 md:p-8"><section className="overflow-hidden rounded-3xl bg-gradient-to-br from-indigo-600 to-brand-blue p-7 text-white shadow-xl"><div className="flex items-start justify-between"><div><p className="text-sm font-bold text-white/75">TIPS BEAUTY</p><h1 className="mt-2 text-2xl font-black">نقاط الجمال</h1><p className="mt-2 text-sm text-white/80">اكسبِي نقاطاً عند اكتمال الطلبات واستخدميها في الطلب القادم.</p></div><Gift className="h-12 w-12 text-white/80"/></div><div className="mt-8 rounded-2xl bg-white/15 p-5 backdrop-blur"><p className="text-sm text-white/80">رصيدك الحالي</p><p className="mt-1 text-4xl font-black">{points.toLocaleString()} <span className="text-lg">نقطة</span></p></div></section><section className="mt-6 rounded-3xl border border-gray-100 bg-white p-6 shadow-sm"><div className="flex items-center gap-2"><Sparkles className="h-5 w-5 text-brand-blue"/><h2 className="font-bold">كيف تستخدمين النقاط؟</h2></div><p className="mt-3 text-sm leading-6 text-gray-600">أدخلي عدد النقاط في صفحة إتمام الطلب. سيعرض النظام قيمة الخصم المسموح بها بعد التحقق من رصيدك والحد الأدنى للاستبدال.</p></section><section className="mt-6 rounded-3xl border border-gray-100 bg-white p-6 shadow-sm"><h2 className="font-bold">سجل النقاط</h2><div className="mt-4 divide-y divide-gray-100">{ledger.length ? ledger.map((item) => <div key={item.id} className="flex items-center justify-between gap-4 py-4"><div className="flex items-center gap-3">{item.points_delta > 0 ? <PlusCircle className="h-5 w-5 text-emerald-500"/> : <MinusCircle className="h-5 w-5 text-rose-500"/>}<div><p className="text-sm font-bold text-gray-800">{item.note || (item.points_delta > 0 ? 'نقاط مكتسبة' : 'استبدال نقاط')}</p><p className="text-xs text-gray-400">{new Date(item.created_at).toLocaleDateString('ar-EG')}{item.order?.order_number ? ` · ${item.order.order_number}` : ''}</p></div></div><b className={item.points_delta > 0 ? 'text-emerald-600' : 'text-rose-600'}>{item.points_delta > 0 ? '+' : ''}{item.points_delta}</b></div>) : <p className="py-8 text-center text-sm text-gray-400">لا توجد حركات نقاط حتى الآن.</p>}</div></section></div>;
};
