import React, { useEffect, useState } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { CheckCircle2, FileUp, Landmark, Loader2, ShieldCheck } from 'lucide-react';
import { supabase } from '../../lib/supabase';
import { useAuth } from '../../context/AuthContext';

type Order = { id: string; order_number: string; total: number; payment_method: string; payment_status: string };
type Method = { code: string; name_ar: string; description_ar: string | null; account_details: Record<string, string> | null };

export const PaymentProofPage: React.FC = () => {
    const { user } = useAuth(); const navigate = useNavigate(); const [params] = useSearchParams();
    const orderId = params.get('order') || ''; const number = params.get('number') || '';
    const [order, setOrder] = useState<Order | null>(null); const [method, setMethod] = useState<Method | null>(null);
    const [reference, setReference] = useState(''); const [file, setFile] = useState<File | null>(null); const [loading, setLoading] = useState(true); const [submitting, setSubmitting] = useState(false); const [error, setError] = useState(''); const [done, setDone] = useState(false);
    useEffect(() => { if (!user || !orderId) { setLoading(false); return; } void (async () => { const { data: orderData, error: orderError } = await supabase.from('orders').select('id,order_number,total,payment_method,payment_status').eq('id', orderId).maybeSingle(); if (orderError || !orderData) { setError('تعذر العثور على الطلب.'); setLoading(false); return; } setOrder(orderData as Order); const { data: methodData } = await supabase.from('payment_methods').select('code,name_ar,description_ar,account_details').eq('code', orderData.payment_method).maybeSingle(); setMethod(methodData as Method | null); setLoading(false); })(); }, [user, orderId]);
    const submit = async (event: React.FormEvent) => { event.preventDefault(); if (!user || !order || !file) { setError('أرفق صورة أو ملف إثبات الدفع أولاً.'); return; } if (file.size > 5 * 1024 * 1024) { setError('حجم الملف يجب أن يكون أقل من 5 ميغابايت.'); return; } setSubmitting(true); setError(''); try { const extension = file.name.split('.').pop()?.toLowerCase() || 'jpg'; const path = `${user.id}/${order.id}/${crypto.randomUUID()}.${extension}`; const { error: uploadError } = await supabase.storage.from('payment-proofs').upload(path, file, { contentType: file.type, upsert: false }); if (uploadError) throw uploadError; const { error: proofError } = await supabase.rpc('submit_payment_proof', { p_order_id: order.id, p_payment_method: order.payment_method, p_amount: order.total, p_transaction_reference: reference.trim() || null, p_proof_path: path }); if (proofError) throw proofError; setDone(true); } catch (err: any) { setError(err.message || 'تعذر إرسال إثبات الدفع'); } finally { setSubmitting(false); } };
    if (loading) return <div className="flex min-h-[50vh] items-center justify-center"><Loader2 className="h-8 w-8 animate-spin text-brand-blue"/></div>;
    if (done) return <div className="mx-auto max-w-lg p-6 text-center"><div className="rounded-3xl border border-emerald-100 bg-white p-10 shadow-sm"><CheckCircle2 className="mx-auto h-16 w-16 text-emerald-500"/><h1 className="mt-4 text-2xl font-bold">تم إرسال إثبات الدفع</h1><p className="mt-2 text-gray-500">سنراجع التحويل ونؤكد الدفع من لوحة الإدارة.</p><button onClick={() => navigate(`/track-order?order=${encodeURIComponent(order?.order_number || number)}`)} className="mt-6 rounded-xl bg-brand-blue px-6 py-3 font-bold text-white">متابعة الطلب</button></div></div>;
    return <div className="mx-auto max-w-xl p-4 md:p-8"><div className="rounded-3xl border border-gray-100 bg-white p-6 shadow-sm md:p-8"><div className="flex items-center gap-3"><div className="rounded-2xl bg-blue-50 p-3 text-brand-blue"><Landmark className="h-7 w-7"/></div><div><h1 className="text-2xl font-bold">إثبات الدفع</h1><p className="text-sm text-gray-500">الطلب: {order?.order_number || number}</p></div></div>{error && <p className="mt-5 rounded-xl bg-red-50 p-3 text-sm font-bold text-red-600">{error}</p>}<div className="mt-6 rounded-2xl bg-slate-50 p-4"><p className="font-bold">المبلغ المطلوب: {Number(order?.total || 0).toLocaleString()} ج.س</p><p className="mt-1 text-sm text-gray-600">{method?.description_ar || 'أرسل التحويل ثم أرفق إثبات الدفع.'}</p>{method?.account_details && Object.entries(method.account_details).map(([key, value]) => <p key={key} className="mt-2 text-sm text-gray-700"><b>{key.replace('_', ' ')}:</b> {value}</p>)}</div><form onSubmit={submit} className="mt-6 space-y-4"><div><label className="mb-1 block text-sm font-bold">رقم المرجع أو رقم التحويل</label><input value={reference} onChange={(event) => setReference(event.target.value)} placeholder="اختياري لكنه يساعد في سرعة المراجعة" className="w-full rounded-xl border border-gray-200 p-3 outline-none focus:ring-2 focus:ring-brand-blue"/></div><div><label className="mb-1 block text-sm font-bold">صورة أو ملف إثبات الدفع</label><label className="flex cursor-pointer flex-col items-center justify-center rounded-2xl border-2 border-dashed border-blue-200 bg-blue-50/40 p-8 text-center"><FileUp className="h-8 w-8 text-brand-blue"/><b className="mt-2">{file ? file.name : 'اختاري الملف'}</b><small className="mt-1 text-gray-500">JPG أو PNG أو WEBP أو PDF، حتى 5 ميغابايت</small><input type="file" accept="image/jpeg,image/png,image/webp,application/pdf" onChange={(event) => setFile(event.target.files?.[0] || null)} className="hidden"/></label></div><div className="flex items-center gap-2 rounded-xl bg-emerald-50 p-3 text-xs text-emerald-700"><ShieldCheck className="h-4 w-4"/>الملف خاص ولا يراه إلا فريق المراجعة.</div><button disabled={submitting || !order} className="flex w-full items-center justify-center gap-2 rounded-xl bg-brand-blue py-3.5 font-bold text-white disabled:opacity-60">{submitting && <Loader2 className="h-5 w-5 animate-spin"/>}{submitting ? 'جارٍ الإرسال...' : 'إرسال إثبات الدفع'}</button></form></div></div>;
};
