import React, { useEffect, useMemo, useState } from 'react';
import { Check, Copy, Gift, Loader2, Share2, Users } from 'lucide-react';
import { supabase } from '../../lib/supabase';
import { useAuth } from '../../context/AuthContext';

type ReferralReward = { id: string; points_awarded: number; status: string; created_at: string; order: { order_number: string | null } | null };

export const ReferralPage: React.FC = () => {
  const { user } = useAuth(); const [code, setCode] = useState(''); const [rewards, setRewards] = useState<ReferralReward[]>([]); const [loading, setLoading] = useState(true); const [copied, setCopied] = useState(false);
  useEffect(() => { if (!user) return; void (async () => { const [profile, result] = await Promise.all([supabase.from('profiles').select('referral_code').eq('id', user.id).maybeSingle(), supabase.from('referral_rewards').select('id,points_awarded,status,created_at,order:orders(order_number)').order('created_at', { ascending: false })]); setCode(profile.data?.referral_code || ''); setRewards((result.data || []) as unknown as ReferralReward[]); setLoading(false); })(); }, [user]);
  const shareText = useMemo(() => `تسوقي من تيبس بيوتي باستخدام كود الإحالة ${code} عند الدفع.`, [code]);
  const copy = async () => { if (!code) return; await navigator.clipboard.writeText(code); setCopied(true); window.setTimeout(() => setCopied(false), 1800); };
  const share = async () => { if (navigator.share) { await navigator.share({ title: 'تيبس بيوتي', text: shareText }); } else { await copy(); } };
  if (loading) return <div className="flex min-h-[50vh] items-center justify-center"><Loader2 className="h-8 w-8 animate-spin text-brand-blue" /></div>;
  const earned = rewards.filter((item) => item.status === 'available').reduce((sum, item) => sum + Number(item.points_awarded), 0);
  return <div className="mx-auto max-w-3xl p-4 md:p-8"><section className="overflow-hidden rounded-[2rem] bg-gradient-to-l from-brand-blue to-sky-600 p-7 text-white shadow-xl"><div className="flex items-start justify-between gap-4"><div><span className="inline-flex rounded-full bg-white/15 px-3 py-1 text-xs font-black">برنامج الإحالة</span><h1 className="mt-4 text-3xl font-black">شاركي الجمال واكسبي نقاطاً</h1><p className="mt-3 max-w-lg text-sm leading-7 text-white/85">عندما تكمل عميلة جديدة أول طلب لها باستخدام كودك، تحصلين على <b>100 نقطة جمال</b>.</p></div><Gift className="h-12 w-12 shrink-0 text-blue-100" /></div><div className="mt-7 rounded-2xl bg-white/15 p-5 backdrop-blur"><p className="text-xs font-bold text-white/75">كود الإحالة الخاص بك</p><div className="mt-2 flex flex-wrap items-center justify-between gap-3"><strong className="font-mono text-2xl tracking-wider">{code || 'جارٍ الإنشاء...'}</strong><div className="flex gap-2"><button onClick={() => void copy()} className="inline-flex items-center gap-1.5 rounded-xl bg-white px-3 py-2 text-xs font-black text-brand-blue">{copied ? <Check className="h-4 w-4" /> : <Copy className="h-4 w-4" />}{copied ? 'تم النسخ' : 'نسخ'}</button><button onClick={() => void share()} className="inline-flex items-center gap-1.5 rounded-xl border border-white/40 px-3 py-2 text-xs font-black text-white"><Share2 className="h-4 w-4" />مشاركة</button></div></div></div></section><div className="mt-6 grid grid-cols-1 gap-4 sm:grid-cols-2"><article className="rounded-3xl border border-slate-100 bg-white p-6 shadow-sm"><Users className="h-6 w-6 text-brand-blue" /><p className="mt-4 text-sm text-slate-500">إحالات مكتملة</p><p className="mt-1 text-3xl font-black text-slate-900">{rewards.length}</p></article><article className="rounded-3xl border border-emerald-100 bg-emerald-50 p-6"><Gift className="h-6 w-6 text-emerald-600" /><p className="mt-4 text-sm text-emerald-700">نقاط مكتسبة من الإحالة</p><p className="mt-1 text-3xl font-black text-emerald-800">{earned.toLocaleString()}</p></article></div><section className="mt-6 rounded-3xl border border-slate-100 bg-white p-6 shadow-sm"><h2 className="font-black text-slate-900">سجل مكافآت الإحالة</h2>{rewards.length ? <div className="mt-4 divide-y divide-slate-100">{rewards.map((reward) => <div key={reward.id} className="flex items-center justify-between gap-4 py-4"><div><p className="font-bold text-slate-800">مكافأة إحالة</p><p className="mt-1 text-xs text-slate-400">{new Date(reward.created_at).toLocaleDateString('ar-EG')}{reward.order?.order_number ? ` · ${reward.order.order_number}` : ''}</p></div><b className="text-emerald-600">+{reward.points_awarded} نقطة</b></div>)}</div> : <p className="mt-4 text-sm leading-6 text-slate-500">لم تكتمل إحالات بعد. شاركي الكود مع صديقاتك، وتضاف المكافأة بعد أول طلب مسلّم.</p>}</section></div>;
};
